/* relacional_rocaplan: */

CREATE DATABASE ROCAPLAN;
USE ROCAPLAN;

CREATE TABLE USUARIOS (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(60) NOT NULL,
    USU_EMAIL VARCHAR(60) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(16) NOT NULL
);

CREATE TABLE PRODUTOS (
    PRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME VARCHAR(40) NOT NULL,
    PRO_VALOR_UNITARIO FLOAT NOT NULL,
    PRO_QUANTIDADE INTEGER NOT NULL,
    FK_USU_ID INTEGER,
    FK_TPR_ID INTEGER
);

CREATE TABLE DESPESAS (
    DES_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DES_DATA DATE NOT NULL,
    DES_NOME VARCHAR(60) NOT NULL,
    DES_QUANTIDADE INTEGER,
    DES_CONSUMO INTEGER,
    DES_VALOR FLOAT NOT NULL,
    FK_TDE_ID INTEGER,
    FK_USU_ID INTEGER
);

CREATE TABLE VENDAS (
    VEN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VEN_DATA DATE NOT NULL,
    VEN_NOME_CLIENTE VARCHAR(60),
    VEN_SITUACAO_PAGAMENTO TINYINT(1) NOT NULL,
    FK_USU_ID INTEGER,
    VEN_VALOR_TOTAL FLOAT
);

CREATE TABLE TIPO_PRODUTOS (
    TPR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TPR_NOME VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE TIPO_DESPESA (
    TDE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TDE_NOME VARCHAR(15) NOT NULL UNIQUE,
    FK_CDE_ID INTEGER
);

CREATE TABLE CATEGORIA_DESPESA (
    CDE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CDE_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE PRODUTOS_VENDIDOS (
    FK_PRO_ID INTEGER,
    FK_VEN_ID INTEGER,
    PRV_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRV_QUANTIDADE INTEGER NOT NULL
);
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_3
    FOREIGN KEY (FK_TPR_ID)
    REFERENCES TIPO_PRODUTOS (TPR_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DESPESAS ADD CONSTRAINT FK_DESPESAS_2
    FOREIGN KEY (FK_TDE_ID)
    REFERENCES TIPO_DESPESA (TDE_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE DESPESAS ADD CONSTRAINT FK_DESPESAS_3
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_2
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE TIPO_DESPESA ADD CONSTRAINT FK_TIPO_DESPESA_2
    FOREIGN KEY (FK_CDE_ID)
    REFERENCES CATEGORIA_DESPESA (CDE_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTOS_VENDIDOS ADD CONSTRAINT FK_PRODUTOS_VENDIDOS_2
    FOREIGN KEY (FK_PRO_ID)
    REFERENCES PRODUTOS (PRO_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTOS_VENDIDOS ADD CONSTRAINT FK_PRODUTOS_VENDIDOS_3
    FOREIGN KEY (FK_VEN_ID)
    REFERENCES VENDAS (VEN_ID)
    ON DELETE SET NULL;
    
INSERT INTO TIPO_PRODUTOS(TPR_NOME) VALUES ("Fruta"), ("Grãos"), ("Legume"), ("Verdura");
INSERT INTO CATEGORIA_DESPESA(CDE_NOME) VALUES ("Ferramentas e Insumos"), ("Infraestrutura");
INSERT INTO TIPO_DESPESA(TDE_NOME, FK_CDE_ID) VALUES ("Adubo", 1), ("Ferramentas", 1), ("Sementes", 1), ("Água", 2), ("Energia", 2);
-- Esse é só para funcionar as inserções sem o login estar feito
INSERT INTO USUARIOS(USU_NOME, USU_EMAIL, USU_SENHA) VALUES("RoçaPlan", "rocaplan@gmail.com", "alfaceEbatata");