/* Lógico_1: */

CREATE DATABASE TRASHTRACK;

USE TRASHTRACK;

CREATE TABLE MORADORES_COLETORES (
    MOC_EMAIL VARCHAR(200) NOT NULL,
    MOC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MOC_SENHA VARCHAR(50) NOT NULL,
    MOC_NOME VARCHAR(100) NOT NULL,
    MOC_CPF VARCHAR(14) NOT NULL,
    MOC_DATA_NASCIMENTO DATE NOT NULL,
    MOC_QUANTIDADE_LIXO_COLETADO INTEGER NOT NULL,
    MOC_PONTUACAO INTEGER NOT NULL,
    MOC_ATIVO BOOLEAN NOT NULL,
    MOC_QUANTIDADE_LIXO_RECICLADO INTEGER NOT NULL,
    UNIQUE (MOC_EMAIL, MOC_CPF, MOC_ID)
);

CREATE TABLE ADMINISTRADORES (
    ADM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ADM_EMAIL VARCHAR(200) NOT NULL UNIQUE,
    ADM_SENHA VARCHAR(200) NOT NULL
);

CREATE TABLE PONTOS_DE_COLETA (
    PON_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PON_TIPO_LIXO ENUM('OR','OL','RE','EL') NOT NULL,
    PON_COORDENADA POINT NOT NULL,
    PON_RUA VARCHAR(200) NOT NULL,
    PON_NUMERO VARCHAR(200) NOT NULL,
    PON_CIDADE VARCHAR(200) NOT NULL,
    PON_BAIRRO VARCHAR(200) NOT NULL,
    PON_COMPLEMENTO VARCHAR(200) NOT NULL,
    PON_COLETADO BOOLEAN NOT NULL,
    PON_DESATIVADO BOOLEAN NOT NULL,
    FK_MORADORES_COLETORES_MOC_ID INTEGER
);

CREATE TABLE DENUNCIAS (
    DEN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEN_DESCRICAO VARCHAR(500) NOT NULL,
    DEN_DATA_DENUNCIA DATE NOT NULL,
    DEN_DESATIVADO BOOLEAN NOT NULL,
    FK_PONTOS_DE_COLETA_PON_ID INTEGER
);

CREATE TABLE NOTIFICACOES (
    NOT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOT_DESCRICAO VARCHAR(200) NOT NULL,
    FK_MORADORES_COLETORES_MOC_ID INTEGER,
    FK_PONTOS_DE_COLETA_PON_ID INTEGER
);
 
ALTER TABLE PONTOS_DE_COLETA ADD CONSTRAINT FK_PONTOS_DE_COLETA_2
    FOREIGN KEY (FK_MORADORES_COLETORES_MOC_ID)
    REFERENCES MORADORES_COLETORES (MOC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_2
    FOREIGN KEY (FK_PONTOS_DE_COLETA_PON_ID)
    REFERENCES PONTOS_DE_COLETA (PON_ID)
    ON DELETE CASCADE;
 
ALTER TABLE NOTIFICACOES ADD CONSTRAINT FK_NOTIFICACOES_2
    FOREIGN KEY (FK_MORADORES_COLETORES_MOC_ID)
    REFERENCES MORADORES_COLETORES (MOC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE NOTIFICACOES ADD CONSTRAINT FK_NOTIFICACOES_3
    FOREIGN KEY (FK_PONTOS_DE_COLETA_PON_ID)
    REFERENCES PONTOS_DE_COLETA (PON_ID)
    ON DELETE SET NULL;