ALTER TABLE `DENUNCIAS` DROP FOREIGN KEY `FK_DENUNCIAS_2`;
--> statement-breakpoint
ALTER TABLE `DENUNCIAS` DROP FOREIGN KEY `FK_DENUNCIAS_3`;
--> statement-breakpoint
ALTER TABLE `GERENTES` DROP FOREIGN KEY `FK_GERENTES_2`;
--> statement-breakpoint
ALTER TABLE `GERENTES` DROP FOREIGN KEY `FK_GERENTES_3`;
--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` DROP FOREIGN KEY `FK_SERVICOS_TERCEIRIZADOS_2`;
--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP FOREIGN KEY `FK_TAREFAS_2`;
--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP FOREIGN KEY `FK_TAREFAS_3`;
--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP FOREIGN KEY `FK_TAREFAS_4`;
--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP FOREIGN KEY `FK_TAREFAS_5`;
--> statement-breakpoint
ALTER TABLE `ADMINISTRADORES` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `AREAS` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `CIDADOES` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `DEPARTAMENTOS` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `GERENTES` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `STATUS` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP PRIMARY KEY;--> statement-breakpoint
ALTER TABLE `ADMINISTRADORES` MODIFY COLUMN `ADM_ID_PRIVADO` bigint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `AREAS` MODIFY COLUMN `ARE_ID` bigint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `CIDADOES` MODIFY COLUMN `CID_ID_PRIVADO` bigint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `CIDADOES` MODIFY COLUMN `CID_ATIVADO` tinyint NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` MODIFY COLUMN `DEN_ID_PRIVADO` bigint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` MODIFY COLUMN `DEN_CREATED_AT` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `DENUNCIAS` MODIFY COLUMN `DEN_UPDATED_AT` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP;--> statement-breakpoint
ALTER TABLE `DEPARTAMENTOS` MODIFY COLUMN `DEP_ID` tinyint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `GERENTES` MODIFY COLUMN `GER_ID_PRIVADO` bigint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` MODIFY COLUMN `SER_ID_PRIVADO` bigint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` MODIFY COLUMN `SER_ATIVADO` tinyint NOT NULL DEFAULT 1;--> statement-breakpoint
ALTER TABLE `STATUS` MODIFY COLUMN `STA_ID` tinyint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `TAREFAS` MODIFY COLUMN `TAR_ID_PRIVADO` bigint unsigned AUTO_INCREMENT NOT NULL;--> statement-breakpoint
ALTER TABLE `TAREFAS` MODIFY COLUMN `TAR_CREATED_AT` timestamp NOT NULL DEFAULT (now());--> statement-breakpoint
ALTER TABLE `TAREFAS` MODIFY COLUMN `TAR_CHAMADOS` tinyint unsigned;--> statement-breakpoint
ALTER TABLE `ADMINISTRADORES` ADD PRIMARY KEY(`ADM_ID_PRIVADO`);--> statement-breakpoint
ALTER TABLE `AREAS` ADD PRIMARY KEY(`ARE_ID`);--> statement-breakpoint
ALTER TABLE `CIDADOES` ADD PRIMARY KEY(`CID_ID_PRIVADO`);--> statement-breakpoint
ALTER TABLE `DENUNCIAS` ADD PRIMARY KEY(`DEN_ID_PRIVADO`);--> statement-breakpoint
ALTER TABLE `DEPARTAMENTOS` ADD PRIMARY KEY(`DEP_ID`);--> statement-breakpoint
ALTER TABLE `GERENTES` ADD PRIMARY KEY(`GER_ID_PRIVADO`);--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` ADD PRIMARY KEY(`SER_ID_PRIVADO`);--> statement-breakpoint
ALTER TABLE `STATUS` ADD PRIMARY KEY(`STA_ID`);--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD PRIMARY KEY(`TAR_ID_PRIVADO`);--> statement-breakpoint
ALTER TABLE `CIDADOES` ADD `CID_FOTO` varchar(1024);--> statement-breakpoint
ALTER TABLE `CIDADOES` ADD `CID_TOKEN` varchar(1024);--> statement-breakpoint
ALTER TABLE `DENUNCIAS` ADD `DEN_LATITUDE` decimal(13,10) NOT NULL;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` ADD `DEN_LONGITUDE` decimal(13,10) NOT NULL;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` ADD `FK_CID_ID_PRIVADO` bigint unsigned;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` ADD `FK_STA_ID` tinyint unsigned;--> statement-breakpoint
ALTER TABLE `GERENTES` ADD `FK_DEP_ID` tinyint unsigned NOT NULL;--> statement-breakpoint
ALTER TABLE `GERENTES` ADD `FK_ADM_ID_PRIVADO` bigint unsigned NOT NULL;--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` ADD `SER_FOTO` varchar(1024);--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` ADD `FK_ARE_ID` bigint unsigned NOT NULL;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD `FK_DEN_ID_PRIVADO` bigint unsigned;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD `FK_STA_ID` tinyint unsigned;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD `FK_SER_ID_PRIVADO` bigint unsigned;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD `FK_GER_ID_PRIVADO` bigint unsigned;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` ADD CONSTRAINT `DENUNCIAS_FK_CID_ID_PRIVADO_CIDADOES_CID_ID_PRIVADO_fk` FOREIGN KEY (`FK_CID_ID_PRIVADO`) REFERENCES `CIDADOES`(`CID_ID_PRIVADO`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` ADD CONSTRAINT `DENUNCIAS_FK_STA_ID_STATUS_STA_ID_fk` FOREIGN KEY (`FK_STA_ID`) REFERENCES `STATUS`(`STA_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `GERENTES` ADD CONSTRAINT `GERENTES_FK_DEP_ID_DEPARTAMENTOS_DEP_ID_fk` FOREIGN KEY (`FK_DEP_ID`) REFERENCES `DEPARTAMENTOS`(`DEP_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `GERENTES` ADD CONSTRAINT `GERENTES_FK_ADM_ID_PRIVADO_ADMINISTRADORES_ADM_ID_PRIVADO_fk` FOREIGN KEY (`FK_ADM_ID_PRIVADO`) REFERENCES `ADMINISTRADORES`(`ADM_ID_PRIVADO`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` ADD CONSTRAINT `SERVICOS_TERCEIRIZADOS_FK_ARE_ID_AREAS_ARE_ID_fk` FOREIGN KEY (`FK_ARE_ID`) REFERENCES `AREAS`(`ARE_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD CONSTRAINT `TAREFAS_FK_DEN_ID_PRIVADO_DENUNCIAS_DEN_ID_PRIVADO_fk` FOREIGN KEY (`FK_DEN_ID_PRIVADO`) REFERENCES `DENUNCIAS`(`DEN_ID_PRIVADO`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD CONSTRAINT `TAREFAS_FK_STA_ID_STATUS_STA_ID_fk` FOREIGN KEY (`FK_STA_ID`) REFERENCES `STATUS`(`STA_ID`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD CONSTRAINT `TAREFAS_FK_SER_ID_PRIVADO_SERVICOS_TERCEIRIZADOS_SER_ID_PRIVADO_fk` FOREIGN KEY (`FK_SER_ID_PRIVADO`) REFERENCES `SERVICOS_TERCEIRIZADOS`(`SER_ID_PRIVADO`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD CONSTRAINT `TAREFAS_FK_GER_ID_PRIVADO_GERENTES_GER_ID_PRIVADO_fk` FOREIGN KEY (`FK_GER_ID_PRIVADO`) REFERENCES `GERENTES`(`GER_ID_PRIVADO`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` DROP COLUMN `DEN_COORDENADA`;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` DROP COLUMN `FK_CIDADOES_CID_ID_PRIVADO`;--> statement-breakpoint
ALTER TABLE `DENUNCIAS` DROP COLUMN `FK_STATUS_STA_ID`;--> statement-breakpoint
ALTER TABLE `GERENTES` DROP COLUMN `FK_DEPARTAMENTOS_DEP_ID`;--> statement-breakpoint
ALTER TABLE `GERENTES` DROP COLUMN `FK_ADMINISTRADORES_ADM_ID_PRIVADO`;--> statement-breakpoint
ALTER TABLE `SERVICOS_TERCEIRIZADOS` DROP COLUMN `FK_AREAS_ARE_ID`;--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP COLUMN `FK_DENUNCIAS_DEN_ID_PRIVADO`;--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP COLUMN `FK_STATUS_STA_ID`;--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP COLUMN `FK_SERVICOS_TERCEIRIZADOS_SER_ID_PRIVADO`;--> statement-breakpoint
ALTER TABLE `TAREFAS` DROP COLUMN `FK_GERENTES_GER_ID_PRIVADO`;