ALTER TABLE `TAREFAS` DROP FOREIGN KEY `TAREFAS_FK_SER_ID_PRIVADO_SERVICOS_TERCEIRIZADOS_SER_ID_PRIVADO_fk`;
--> statement-breakpoint
ALTER TABLE `TAREFAS` ADD CONSTRAINT `TAREFAS_FK_SER_ID_PRIVADO_SERVICOS_TERCEIRIZADOS_SER_ID_PRIVADO_fk` FOREIGN KEY (`FK_SER_ID_PRIVADO`) REFERENCES `SERVICOS_TERCEIRIZADOS`(`SER_ID_PRIVADO`) ON DELETE no action ON UPDATE cascade;